[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/urfave/cli"
  version = "=v1.21.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "=v1.7.3"

[[constraint]]
  name = "github.com/cikupin/go-saga"
  version = "=v1.0.0"
